<a href="https://colab.research.google.com/github/dean790814/chatbot/blob/master/20190806.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
"""透過Numpy建立一維數組
索引       學號
 0          1
 1          2
 2          3
 3          4"""
#程式
import numpy as np
vector = np.array ([1,2,3,4])
matrix = np.array ([[1,"Tom"],[2,"Joay"],[3,"Johnry"],[4,"Frank"]])
print(vector)
print(matrix)

[1 2 3 4]
[['1' 'Tom']
 ['2' 'Joay']
 ['3' 'Johnry']
 ['4' 'Frank']]


In [6]:
""""透過Numpy建立二維數組
1 Tom
2 Joey
3 Johnry
4 Frank"""
#獲取numpy中數組的資料
a = np.arange(15).reshape(3,5)
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 5)
15


In [0]:
#numpy透過genfromtxt()讀取檔案
import numpy as up
nfl = np.genfromtxt("house-prices.csv",delimiter =",")

In [11]:
from google.colab import files
uploaded = files.upload()


Saving house-prices.csv to house-prices (1).csv


In [13]:

import numpy as up
nfl = np.genfromtxt("house-prices.csv",delimiter =",")
print(nfl)

[[      nan       nan       nan ...       nan       nan       nan]
 [1.000e+00 1.143e+05 1.790e+03 ... 2.000e+00       nan       nan]
 [2.000e+00 1.142e+05 2.030e+03 ... 3.000e+00       nan       nan]
 ...
 [1.260e+02 1.135e+05 2.070e+03 ... 2.000e+00       nan       nan]
 [1.270e+02 1.499e+05 2.020e+03 ... 1.000e+00       nan       nan]
 [1.280e+02 1.246e+05 2.250e+03 ... 4.000e+00       nan       nan]]


In [14]:

#加入參數後的呈現
#na表示讀取是空的,han是數劇類型轉換出錯.genfromtxt()對於han的類型可轉換
#dtype設定"u75",表示每個值都是75byte的un
nfl = np.genfromtxt("house-prices.csv",dtype ="U75" ,skip_header = 1 ,delimiter =",")
print(nfl)

[['1' '114300' '1790' ... '2' 'No' 'East']
 ['2' '114200' '2030' ... '3' 'No' 'East']
 ['3' '114800' '1740' ... '1' 'No' 'East']
 ...
 ['126' '113500' '2070' ... '2' 'No' 'North']
 ['127' '149900' '2020' ... '1' 'No' 'West']
 ['128' '124600' '2250' ... '4' 'No' 'North']]


In [16]:
#多維數組的切片
import numpy as np
martix =np.array([[5,10,15],[20,25,30],[35,40,45]])
print(martix[:,1])
print(martix[:,0:2])
print(martix[1:3,:])
print(martix[1:3,0:2])

[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]
[[20 25 30]
 [35 40 45]]
[[20 25]
 [35 40]]


In [17]:
#數組比較產生布林值
import numpy as np
martix =np.array([[5,0,15],[20,25,30],[35,40,45]])
m =(martix ==25)
print(m)

[[False False False]
 [False  True False]
 [False False False]]


In [20]:
import numpy as np
martix =np.array([[5,10,15],[20,25,30],[35,40,45]])
second_column_25 = (martix[:,1] ==25)
print(second_column_25)
print(martix[second_column_25,:])

vector = np.array([5,10,11,12])
equalto_five_and_ten =(vector == 5) & (vector == 10)
print(equalto_five_and_ten)

vector = np.array([5,10,11,12])
equalto_five_and_ten =(vector == 5) | (vector == 10)
print(equalto_five_and_ten)

[False  True False]
[[20 25 30]]
[False False False False]
[ True  True False False]


In [21]:
#替換空值
import numpy as np
martix =np.array([["5","10","15"],["20","25","30"],["35","40",""]])
second_column_25 = (martix[:,:] =="")
martix[second_column_25]="0"
print(martix)
#統計方法
vector = np.array([10,20,30,40])
print(vector.sum())
martix =np.array([[5,10,15],[20,25,30],[35,40,45]])
print(martix.sum(axis=1))



[['5' '10' '15']
 ['20' '25' '30']
 ['35' '40' '0']]
100
[ 30  75 120]
